//
// File generated by rootcint at Thu May  2 09:44:00 2013

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME MuonIsoMVACint
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "MuonIsoMVACint.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void MuonIsoMVA_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void MuonIsoMVA_Dictionary();
   static void *new_MuonIsoMVA(void *p = 0);
   static void *newArray_MuonIsoMVA(Long_t size, void *p);
   static void delete_MuonIsoMVA(void *p);
   static void deleteArray_MuonIsoMVA(void *p);
   static void destruct_MuonIsoMVA(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::MuonIsoMVA*)
   {
      ::MuonIsoMVA *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::MuonIsoMVA),0);
      static ::ROOT::TGenericClassInfo 
         instance("MuonIsoMVA", "./MuonIsoMVA.h", 17,
                  typeid(::MuonIsoMVA), DefineBehavior(ptr, ptr),
                  0, &MuonIsoMVA_Dictionary, isa_proxy, 0,
                  sizeof(::MuonIsoMVA) );
      instance.SetNew(&new_MuonIsoMVA);
      instance.SetNewArray(&newArray_MuonIsoMVA);
      instance.SetDelete(&delete_MuonIsoMVA);
      instance.SetDeleteArray(&deleteArray_MuonIsoMVA);
      instance.SetDestructor(&destruct_MuonIsoMVA);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::MuonIsoMVA*)
   {
      return GenerateInitInstanceLocal((::MuonIsoMVA*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::MuonIsoMVA*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void MuonIsoMVA_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::MuonIsoMVA*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_MuonIsoMVA(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MuonIsoMVA : new ::MuonIsoMVA;
   }
   static void *newArray_MuonIsoMVA(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::MuonIsoMVA[nElements] : new ::MuonIsoMVA[nElements];
   }
   // Wrapper around operator delete
   static void delete_MuonIsoMVA(void *p) {
      delete ((::MuonIsoMVA*)p);
   }
   static void deleteArray_MuonIsoMVA(void *p) {
      delete [] ((::MuonIsoMVA*)p);
   }
   static void destruct_MuonIsoMVA(void *p) {
      typedef ::MuonIsoMVA current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::MuonIsoMVA

/********************************************************
* MuonIsoMVACint.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableMuonIsoMVACint();

extern "C" void G__set_cpp_environmentMuonIsoMVACint() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("MuonIsoMVA.h");
  G__cpp_reset_tagtableMuonIsoMVACint();
}
#include <new>
extern "C" int G__cpp_dllrevMuonIsoMVACint() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* MuonIsoMVA */
static int G__MuonIsoMVACint_659_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MuonIsoMVA* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MuonIsoMVA[n];
     } else {
       p = new((void*) gvp) MuonIsoMVA[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new MuonIsoMVA;
     } else {
       p = new((void*) gvp) MuonIsoMVA;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MuonIsoMVA*) G__getstructoffset())->Initialize(*((string*) G__int(libp->para[0])), (MuonIsoMVA::MVAType) G__int(libp->para[1])
, *((string*) G__int(libp->para[2])), *((string*) G__int(libp->para[3]))
, *((string*) G__int(libp->para[4])), *((string*) G__int(libp->para[5])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((MuonIsoMVA*) G__getstructoffset())->Initialize(*((string*) G__int(libp->para[0])), (MuonIsoMVA::MVAType) G__int(libp->para[1])
, *((vector<std::string>*) G__int(libp->para[2])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((const MuonIsoMVA*) G__getstructoffset())->IsInitialized());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((MuonIsoMVA*) G__getstructoffset())->MVAValue(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8]), (double) G__double(libp->para[9])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((MuonIsoMVA*) G__getstructoffset())->MVAValue(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (double) G__double(libp->para[7])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((MuonIsoMVA*) G__getstructoffset())->MVAValue((double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((MuonIsoMVA*) G__getstructoffset())->MVAValue(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (bool) G__int(libp->para[2]), (bool) G__int(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8]), (double) G__double(libp->para[9])
, (double) G__double(libp->para[10]), (double) G__double(libp->para[11])
, (double) G__double(libp->para[12]), (double) G__double(libp->para[13])
, (double) G__double(libp->para[14]), (double) G__double(libp->para[15])
, (double) G__double(libp->para[16]), (double) G__double(libp->para[17])
, (double) G__double(libp->para[18])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__MuonIsoMVACint_659_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((MuonIsoMVA*) G__getstructoffset())->MVAValue(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (double) G__double(libp->para[7])
, (double) G__double(libp->para[8]), (double) G__double(libp->para[9])
, (double) G__double(libp->para[10]), (double) G__double(libp->para[11])
, (double) G__double(libp->para[12]), (double) G__double(libp->para[13])
, (double) G__double(libp->para[14]), (double) G__double(libp->para[15])
, (double) G__double(libp->para[16]), (double) G__double(libp->para[17])
, (double) G__double(libp->para[18]), (double) G__double(libp->para[19])));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__MuonIsoMVACint_659_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   MuonIsoMVA* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new MuonIsoMVA(*(MuonIsoMVA*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef MuonIsoMVA G__TMuonIsoMVA;
static int G__MuonIsoMVACint_659_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (MuonIsoMVA*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((MuonIsoMVA*) (soff+(sizeof(MuonIsoMVA)*i)))->~G__TMuonIsoMVA();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (MuonIsoMVA*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((MuonIsoMVA*) (soff))->~G__TMuonIsoMVA();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__MuonIsoMVACint_659_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   MuonIsoMVA* dest = (MuonIsoMVA*) G__getstructoffset();
   *dest = *(MuonIsoMVA*) libp->para[0].ref;
   const MuonIsoMVA& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* MuonIsoMVA */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncMuonIsoMVACint {
 public:
  G__Sizep2memfuncMuonIsoMVACint(): p(&G__Sizep2memfuncMuonIsoMVACint::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncMuonIsoMVACint::*p)();
};

size_t G__get_sizep2memfuncMuonIsoMVACint()
{
  G__Sizep2memfuncMuonIsoMVACint a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceMuonIsoMVACint() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableMuonIsoMVACint() {

   /* Setting up typedef entry */
   G__search_typename2("Bool_t",103,-1,0,-1);
   G__setnewtype(-1,"Boolean (0=false, 1=true) (bool)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TMVA::Types::EMVA>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLTypescLcLEMVAcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLTypescLcLEMVAgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TMVA::Types::EMVA,less<TString> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLTypescLcLEMVAcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLTypescLcLEMVAgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEfloatcOallocatorlEfloatgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Float_t*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEfloatmUcOallocatorlEfloatmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEfloatmUcOallocatorlEfloatmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<float*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<VariableInfo>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMVA::VariableInfo>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ClassInfo*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMVA::ClassInfo*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<Char_t,UInt_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_pairlEcharcOunsignedsPintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<Char_t,UInt_t> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<char,unsigned int> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Event*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMVA::Event*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Char_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEcharcOallocatorlEchargRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Int_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixDSym*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMatrixTSym<double>*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Double_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEdoublecOallocatorlEdoublegRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<Double_t> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<EMsgType,std::string>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TMVA::EMsgType,string>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TMVA::EMsgType,string,less<TMVA::EMsgType> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TreeInfo>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMVA::TreeInfo>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,std::vector<TreeInfo> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,vector<TMVA::TreeInfo,allocator<TMVA::TreeInfo> > >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,vector<TMVA::TreeInfo,allocator<TMVA::TreeInfo> >,less<TString> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,Bool_t>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,bool,less<string> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,IMethod*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TMVA::IMethod*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<TString,TMVA::IMethod*,less<TString> >",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TMVA::Reader*>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* MuonIsoMVA */
static void G__setup_memvarMuonIsoMVA(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA));
   { MuonIsoMVA *p; p=(MuonIsoMVA*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType),-1,-2,1,G__FastAllocString(2048).Format("kIsoDeltaR=%lldLL",(long long)MuonIsoMVA::kIsoDeltaR).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType),-1,-2,1,G__FastAllocString(2048).Format("kIsoDeltaRV1=%lldLL",(long long)MuonIsoMVA::kIsoDeltaRV1).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType),-1,-2,1,G__FastAllocString(2048).Format("kIsoRings=%lldLL",(long long)MuonIsoMVA::kIsoRings).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType),-1,-2,1,G__FastAllocString(2048).Format("kIsoCombined=%lldLL",(long long)MuonIsoMVA::kIsoCombined).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin),-1,-2,1,G__FastAllocString(2048).Format("kLowPtBarrel=%lldLL",(long long)MuonIsoMVA::kLowPtBarrel).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin),-1,-2,1,G__FastAllocString(2048).Format("kLowPtEndcap=%lldLL",(long long)MuonIsoMVA::kLowPtEndcap).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin),-1,-2,1,G__FastAllocString(2048).Format("kHighPtBarrel=%lldLL",(long long)MuonIsoMVA::kHighPtBarrel).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin),-1,-2,1,G__FastAllocString(2048).Format("kHighPtEndCap=%lldLL",(long long)MuonIsoMVA::kHighPtEndCap).data(),0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR),G__defined_typename("vector<TMVA::Reader*>"),-1,2,"fTMVAReader=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__MuonIsoMVACintLN_string),-1,-1,2,"fMethodname=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,G__defined_typename("Bool_t"),-1,2,"fIsInitialized=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_Pt=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_Eta=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_ChargedIso_DR0p0To0p1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_ChargedIso_DR0p1To0p2=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_ChargedIso_DR0p2To0p3=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_ChargedIso_DR0p3To0p4=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_ChargedIso_DR0p4To0p5=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_GammaIso_DR0p0To0p1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_GammaIso_DR0p1To0p2=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_GammaIso_DR0p2To0p3=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_GammaIso_DR0p3To0p4=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_GammaIso_DR0p4To0p5=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_NeutralHadronIso_DR0p0To0p1=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_NeutralHadronIso_DR0p1To0p2=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_NeutralHadronIso_DR0p2To0p3=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_NeutralHadronIso_DR0p3To0p4=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_NeutralHadronIso_DR0p4To0p5=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuRelIsoPFCharged=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuRelIsoPFNeutral=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuRelIsoPFPhotons=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuDeltaRMean=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuDeltaRSum=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuDensity=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuDZ=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuIP2d=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuRelIsoPFChargedDR04=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuRelIsoPFNePhCorrDR04=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuDeltaRSumCharged=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fMVAVar_MuDeltaRMeanCharged=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarMuonIsoMVACint() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncMuonIsoMVA(void) {
   /* MuonIsoMVA */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA));
   G__memfunc_setup("MuonIsoMVA",942,G__MuonIsoMVACint_659_0_1, 105, G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__MuonIsoMVACint_659_0_2, 121, -1, -1, 0, 6, 1, 1, 0, 
"u 'string' - 0 - methodName i 'MuonIsoMVA::MVAType' - 0 - type "
"u 'string' - 0 - Pt10To20BarrelWeights u 'string' - 0 - Pt10To20EndcapWeights "
"u 'string' - 0 - Pt20ToInfBarrelWeights u 'string' - 0 - Pt20ToInfEndcapWeights", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Initialize",1042,G__MuonIsoMVACint_659_0_3, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'string' - 0 - methodName i 'MuonIsoMVA::MVAType' - 0 - type "
"u 'vector<string,allocator<string> >' 'vector<std::string>' 0 - weightfiles", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("IsInitialized",1330,G__MuonIsoMVACint_659_0_4, 103, -1, G__defined_typename("Bool_t"), 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MVAValue",737,G__MuonIsoMVACint_659_0_5, 100, -1, -1, 0, 10, 1, 1, 0, 
"d - - 0 - MuPt d - - 0 - MuEta "
"d - - 0 - MuDZ d - - 0 - MuIP2d "
"d - - 0 - MuRelIsoPFCharged d - - 0 - MuRelIsoPFNeutral "
"d - - 0 - MuRelIsoPFPhotons d - - 0 - MuDeltaRSum "
"d - - 0 - MuDeltaRMean d - - 0 - MuDensity", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MVAValue",737,G__MuonIsoMVACint_659_0_6, 100, -1, -1, 0, 8, 1, 1, 0, 
"d - - 0 - MuPt d - - 0 - MuEta "
"d - - 0 - MuRelIsoPFCharged d - - 0 - MuRelIsoPFNeutral "
"d - - 0 - MuRelIsoPFPhotons d - - 0 - MuDeltaRSum "
"d - - 0 - MuDeltaRMean d - - 0 - MuDensity", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MVAValue",737,G__MuonIsoMVACint_659_0_7, 100, -1, -1, 0, 6, 1, 1, 0, 
"d - - 0 - MuPt d - - 0 - MuEta "
"d - - 0 - MuRelIsoPFCharged d - - 0 - MuRelIsoPFNePhCorr "
"d - - 0 - MuDeltaRSumCharged d - - 0 - MuDeltaRMeanCharged", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MVAValue",737,G__MuonIsoMVACint_659_0_8, 100, -1, -1, 0, 19, 1, 1, 0, 
"d - - 0 - MuPt d - - 0 - MuEta "
"g - - 0 - - g - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MVAValue",737,G__MuonIsoMVACint_659_0_9, 100, -1, -1, 0, 20, 1, 1, 0, 
"d - - 0 - MuPt d - - 0 - MuEta "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - - "
"d - - 0 - - d - - 0 - -", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("MuonIsoMVA", 942, G__MuonIsoMVACint_659_0_10, (int) ('i'), G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA), -1, 0, 1, 1, 1, 0, "u 'MuonIsoMVA' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~MuonIsoMVA", 1068, G__MuonIsoMVACint_659_0_11, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__MuonIsoMVACint_659_0_12, (int) ('u'), G__get_linked_tagnum(&G__MuonIsoMVACintLN_MuonIsoMVA), -1, 1, 1, 1, 1, 0, "u 'MuonIsoMVA' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncMuonIsoMVACint() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalMuonIsoMVACint() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcMuonIsoMVACint() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEcharcOallocatorlEchargRsPgR = { "vector<char,allocator<char> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLTypescLcLEMVAcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLTypescLcLEMVAgRsPgRsPgR = { "map<TString,TMVA::Types::EMVA,less<TString>,allocator<pair<const TString,TMVA::Types::EMVA> > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR = { "vector<float*,allocator<float*> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEfloatmUcOallocatorlEfloatmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<float*,allocator<float*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR = { "vector<TMVA::VariableInfo,allocator<TMVA::VariableInfo> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMVA::VariableInfo,allocator<TMVA::VariableInfo> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR = { "vector<TMVA::ClassInfo*,allocator<TMVA::ClassInfo*> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMVA::ClassInfo*,allocator<TMVA::ClassInfo*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_pairlEcharcOunsignedsPintgR = { "pair<char,unsigned int>" , 115 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR = { "vector<pair<char,unsigned int>,allocator<pair<char,unsigned int> > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<char,unsigned int>,allocator<pair<char,unsigned int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR = { "vector<TMVA::Event*,allocator<TMVA::Event*> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMVA::Event*,allocator<TMVA::Event*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR = { "vector<TMatrixTSym<double>*,allocator<TMatrixTSym<double>*> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMatrixTSym<double>*,allocator<TMatrixTSym<double>*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR = { "map<TMVA::EMsgType,string,less<TMVA::EMsgType>,allocator<pair<const TMVA::EMsgType,string> > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR = { "vector<TMVA::TreeInfo,allocator<TMVA::TreeInfo> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMVA::TreeInfo,allocator<TMVA::TreeInfo> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR = { "map<TString,vector<TMVA::TreeInfo,allocator<TMVA::TreeInfo> >,less<TString>,allocator<pair<const TString,vector<TMVA::TreeInfo,allocator<TMVA::TreeInfo> > > > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR = { "map<string,bool,less<string>,allocator<pair<const string,bool> > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR = { "map<TString,TMVA::IMethod*,less<TString>,allocator<pair<const TString,TMVA::IMethod*> > >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_MuonIsoMVA = { "MuonIsoMVA" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType = { "MuonIsoMVA::MVAType" , 101 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin = { "MuonIsoMVA::MVAbin" , 101 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR = { "vector<TMVA::Reader*,allocator<TMVA::Reader*> >" , 99 , -1 };
G__linked_taginfo G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TMVA::Reader*,allocator<TMVA::Reader*> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableMuonIsoMVACint() {
  G__MuonIsoMVACintLN_vectorlEcharcOallocatorlEchargRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_string.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__MuonIsoMVACintLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__MuonIsoMVACintLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLTypescLcLEMVAcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLTypescLcLEMVAgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEfloatmUcOallocatorlEfloatmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_pairlEcharcOunsignedsPintgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_MuonIsoMVA.tagnum = -1 ;
  G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType.tagnum = -1 ;
  G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin.tagnum = -1 ;
  G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR.tagnum = -1 ;
  G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableMuonIsoMVACint() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEcharcOallocatorlEchargRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_string);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLTypescLcLEMVAcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLTypescLcLEMVAgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEfloatmUcOallocatorlEfloatmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEfloatmUcOallocatorlEfloatmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLVariableInfocOallocatorlETMVAcLcLVariableInfogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLClassInfomUcOallocatorlETMVAcLcLClassInfomUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_pairlEcharcOunsignedsPintgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEpairlEcharcOunsignedsPintgRcOallocatorlEpairlEcharcOunsignedsPintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLEventmUcOallocatorlETMVAcLcLEventmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMatrixTSymlEdoublegRmUcOallocatorlETMatrixTSymlEdoublegRmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_maplETMVAcLcLEMsgTypecOstringcOlesslETMVAcLcLEMsgTypegRcOallocatorlEpairlEconstsPTMVAcLcLEMsgTypecOstringgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_maplETStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOvectorlETMVAcLcLTreeInfocOallocatorlETMVAcLcLTreeInfogRsPgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_maplEstringcOboolcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOboolgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_maplETStringcOTMVAcLcLIMethodmUcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTMVAcLcLIMethodmUgRsPgRsPgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_MuonIsoMVA),sizeof(MuonIsoMVA),-1,1280,(char*)NULL,G__setup_memvarMuonIsoMVA,G__setup_memfuncMuonIsoMVA);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAType);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_MuonIsoMVAcLcLMVAbin);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_vectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgR);
   G__get_linked_tagnum_fwd(&G__MuonIsoMVACintLN_reverse_iteratorlEvectorlETMVAcLcLReadermUcOallocatorlETMVAcLcLReadermUgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupMuonIsoMVACint(void) {
  G__check_setup_version(30051515,"G__cpp_setupMuonIsoMVACint()");
  G__set_cpp_environmentMuonIsoMVACint();
  G__cpp_setup_tagtableMuonIsoMVACint();

  G__cpp_setup_inheritanceMuonIsoMVACint();

  G__cpp_setup_typetableMuonIsoMVACint();

  G__cpp_setup_memvarMuonIsoMVACint();

  G__cpp_setup_memfuncMuonIsoMVACint();
  G__cpp_setup_globalMuonIsoMVACint();
  G__cpp_setup_funcMuonIsoMVACint();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncMuonIsoMVACint();
  return;
}
class G__cpp_setup_initMuonIsoMVACint {
  public:
    G__cpp_setup_initMuonIsoMVACint() { G__add_setup_func("MuonIsoMVACint",(G__incsetup)(&G__cpp_setupMuonIsoMVACint)); G__call_setup_funcs(); }
   ~G__cpp_setup_initMuonIsoMVACint() { G__remove_setup_func("MuonIsoMVACint"); }
};
G__cpp_setup_initMuonIsoMVACint G__cpp_setup_initializerMuonIsoMVACint;

